[package]
name = "corvin_ascii_gen"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "corvin_ascii_gen"
path = "src/main.rs"

[dependencies]
image = "0.24"
clap = { version = "4.4", features = ["derive"] }
